- name: Install Docker and prepare environment on Ubuntu
  hosts: all
  become: true
  vars:
    arch_mapping:  
      x86_64: amd64
    new_user: mcatal-d

  tasks:
    - name: Create a new user
      ansible.builtin.user:
        name: "{{ new_user }}"
        state: present
        groups: docker
        append: true

    - name: Ensure the new user has a home directory
      ansible.builtin.file:
        path: "/home/{{ new_user }}"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0755'

    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add Docker group (ensure it's present)
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ new_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install dependencies for build tools
      ansible.builtin.apt:
        name: 
          - make
          - gcc
        state: present

    - name: Clone the Inception repository
      ansible.builtin.git:
        repo: 'https://github.com/Mathis-CATAL-DELBUT/Inception.git'
        dest: "/home/{{ new_user }}/inception"
        single_branch: true
        update: yes
        version: cloud
        force: yes
      become_user: "{{ new_user }}"
      become: true

    - name: Run make in the Inception directory
      ansible.builtin.command:
        cmd: make
        chdir: "/home/{{ new_user }}/inception"
      become_user: "{{ new_user }}"
      become: true
