- name: Create Docker group (if not already present)
  ansible.builtin.group:
    name: docker
    state: present

- name: Create a new user
  ansible.builtin.user:
    name: "{{ new_user }}"
    state: present
    groups: docker
    create_home: yes
    append: true

- name: Ensure remote_tmp directory exists with correct permissions
  file:
    path: "/home/{{ new_user }}/.ansible/tmp"
    state: directory
    mode: '1777'